export const indianaRestaurants = [
	"Harry and Izzy's",
	'Some Guys',
	'317 BBQ',
	'Flatwater',
	"Arnie's",
	'High Velocity',
	"Iaria's",
	'Bru Burger',
	'Vida',
	'Le Peep',
	"Fat Dan's",
	'O P',
	'Alleys Ale House',
	"Puccini's",
	'H C Tavern',
	'Best Bet',
	"Ford's Garage",
	'Wolfies',
	"Eddy's Neighborhood Bar and Grill",
	'Big Woods',
	"Tony's Cafe",
	'Parks Place Pub',
	"Aurelio's",
	"Big Hoffa's",
	"Matt the Miller's Tavern",
	'Grindstone Public House',
];

export const losAngelesRestaurants = [
	'Leos Tacos',
	'Mardis Gras Tuesday',
	'Better Than Sex',
	'Formosa Cafe',
	'Philippe The Original',
	'El Coyote Cafe',
	'Casablanca Restaurant',
	'Apple Pan',
	'Dear John\'s',
	'Canter\'s Deli',
	'Saikai Ramen Bar',
	'SUGARFISH',
	'Hotville Chicken',
	'One More Kitchen',
	'Koreatown Pizza Company',
	'Gol Tong Chicken',
	'Pa Ord Noodle',
	'Jitlada',
	'Eataly',
	'Angelini Osteria',
	'Kagaya',
	'Forage',
	'Salaya',
	'Mi Ranchito Veracruz',
	'Escala K-Town',
	'Concerto',
	'Silver Lake Ramen'
]